---
- hosts: localhost
  gather_facts: false
  connection: local
  vars:
    vcenter_server: "Viana-vCenter-01.testing.lab"
    vcenter_user: "administrator@vsphere.local"
    vcenter_pass: "password"
    datacenter_name: "DC-Central"
    cluster_name: "Cluster-01"
    template_name: "Linux16GB-Ansible-Demo"
    deployed_name: "Linux16GB-Cloned"
  tasks:
  - name: clone template
    community.vmware.vmware_guest:
      hostname: "{{vcenter_server}}"
      username: "{{vcenter_user}}"
      password: "{{vcenter_pass}}"
      validate_certs: false
      template: "{{template_name}}"
      name: "{{deployed_name}}"
      datacenter: "{{datacenter_name}}"
      folder: "/{{ datacenter_name }}/vm/ansible"
      cluster: "{{cluster_name}}"
      datastore: "datastore1"
      networks:
        - name: "VM Network"
          device_type: vmxnet3
          ip: 10.10.1.100
          netmask: 255.255.255.0
          gateway: 10.10.1.1
          type: static
          dns_servers: 8.8.8.8
    delegate_to: localhost